### ISSUE TITLE
Periódico (issn: 0103-1104) sem issues via API

### ISSUE THREAD

**Issue by jfunez** [scieloorg/articles_meta#101]
@fabiobatalha 
Consultando o periódico: **0103-1104** via api do ArticleMeta: 
👉  http://articlemeta.scielo.org/api/v1/issue/identifiers/?collection=spa&issn=0103-1104&format=json

não retorna issues.

Porém no Scielo Manager aparecem issues:
👉 http://manager.scielo.org/journal/436/dash/

**Comment by fabiobatalha** [comment]
@jfunez @jamilatta 

Se trata de uma revista da coleção SciELO BR que também estará presente no SciELO SP.

A equipe de produção pediu que migrassemos as bases de dados. Durante a migração existe um delta onde os issues e artigos estão registrados no Manager, mas ainda não foram processados na Coleção SciELO SP, neste período, as bases issue e artigo ainda estão sem os registros.

**Comment by jfunez** [comment]
👍
