### ISSUE TITLE
Artigos não recuperados no article meta no processamento do OPAC

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#113]
Existe alguns artigos em que o processamento está informando que não consegui retornar no AM.

Ver arquivo em anexo para visualizar os artigos.

[export_failed.txt](https://github.com/scieloorg/articles_meta/files/1401923/export_failed.txt)

**Comment by fabiobatalha** [comment]
O Registro foi removido do Articlemeta

http://articlemeta.scielo.org/api/v1/article/history/?collection=spa&code=S1414-32832017005014103
