### ISSUE TITLE
Corrigir o atributo que libera o uso das citações para o CrossRef.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#114]
Estudando sobre a iniciativa **I4OC**

Verifiquei que o atributo: ```<reference_distribution_opt="any">``` está incorreto no **xmlcrossref** do article meta.

Ver: https://github.com/scieloorg/articles_meta/blob/beta/articlemeta/export_crossref.py#L318

Documentação do I4OC: https://i4oc.org/#faqs

**Comment by gustavofonseca** [comment]
A documentação corroboa a implementação atual e invalida esse ticket: https://support.crossref.org/hc/en-us/articles/214936383-Enabling-references-for-distribution
