### ISSUE TITLE
Ausência de PDF em alguns idiomas

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#115]
Existe alguns artigos que estão sem o PDF em português. 

A Renata Postalli sinalizou que a revista RSP está com PDFs faltando. 

Realizei a seguinte validação:

Peguei um artigo como exemplo para analizar o **PID** é: S0034-89102018000100244, **Título**: Offer of primary care services and detection of tuberculosis incidence in Brazil (**RSP - Saúde Pública**)

Na instância de validação está o com os PDFs em **EN** e **PT**, veja: http://homolog.xml.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102018000100244&lng=pt&nrm=iso&tlng=en

Na produção estamos somente com a versão em **EN**: https://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102018000100244&lng=pt&nrm=iso&tlng=en (Repare que estou utilizando a mesma consulta para o site, apenas alterei o **domínio**).

Verifiquei que o a ausência acontece, pois a fonte que estamos coletando os dados não está nos informando que existe PDFs em **EN** e **PT**.

Para comprovar que a fonte não esta com esses dados de PDF em PT, realizei o seguinte teste: 

Necessário instalar o articlemetaapi
```python 

from articlemeta.client import ThriftClient

# PID do artigo: S0034-89102018000100244
article = cl.document(code='S0034-89102018000100244',
                      collection='spa',
                      fmt="xylose",
                      body=True)

# Método do xylose que estamos utilizando no processamento para obter os PDFs
print(article.fulltexts())

Resultado: 

{'pdf': {u'en': u'http://www.scielosp.org/pdf/rsp/v52/0034-8910-rsp-S1518-87872018052000131.pdf'}, 'html': {u'en': 'http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102018000100244&lng=en&tlng=en'}}

Reparem que o resultado não contém o PDF em PT.
```

**Comment by jamilatta** [comment]
Verifiquei também que os arquivos no sistema de arquivo estão presentes para **EN** e **PT**: 

<img width="1544" alt="screenshot 2018-05-24 14 49 27" src="https://user-images.githubusercontent.com/373745/40502576-bdab4e0c-5f61-11e8-8c18-051e41877a0f.png">

**Comment by jamilatta** [comment]
PSI 
@gustavofonseca

**Comment by gustavofonseca** [comment]
@jamilatta: eu vi, valeu! Vc está olhando isso ou quer eu olhe?

**Comment by jamilatta** [comment]
Exemplo de TOC que apresenta o erro: https://www.scielosp.org/toc/rsp/2018.v52/

**Comment by jamilatta** [comment]
Estava desconfiando do nome do arquivo .pdf no sistema de arquivo, porém minha suspeita foi invalidada. 

Bom somente para "PSI" arquivo **.pdf** tem dois formatos de nome: 

Exemplo: 

**pt_0034-8910-rsp-S1518-87872018052000131.pdf** (Parece que o articlemeta utiliza esse formato)

OU

**0034-8910-rsp-S1518-87872018052000131-pt.pdf**

Eu desconfiei que o primeiro formato não estivesse presente!, mas está! :-(

**Comment by gustavofonseca** [comment]
@fabiobatalha poderia confirmar, mas o procedimento pelo qual o ArticleMeta obtém PDFs, traduções e XMLs dos artigos das coleções da Rede é baseado na coleta dos arquivos <domínio da coleção>/static_pdf_catalog.txt, <domínio da coleção>/static_html_catalog.txt e <domínio da coleção>/static_xml_catalog.txt respectivamente. Isso é, cada coleção produz os 3 arquivos de listagem que são coletados pelo ArticleMeta. O problema é que no caso do SciELO SP há uma dependência circular onde o ArticleMeta espera que o SciELO SP informe os dados citados e vice-versa.

**Comment by gustavofonseca** [comment]
Uma proposta de solução paliativa seria implementar, no contexto do ArticleMeta, um servidor Web que monta o sistema de arquivos que contém os conteúdos estáticos de SciELOSP, gera e serve os arquivos txt que citei na mensagem anterior. 

A ideia é tentar mexer o mínimo possível nas rotinas de manipulação de dados do ArticleMeta, haja vista a fragilidade e risco de regressão, e também preservar o mesmo nível de dependência entre o novo site no ArticleMeta.

**Comment by fabiobatalha** [comment]
@gustavofonseca   essa dependência existe pois o legado nao tem informaçao sobre os PDF's disponíveis. A existência ou nao de um PDF para a apresentaçao de um link é testada em tempo de execuçao no momento do acesso do usuário ao site, verificando a disponibilidade do arquivo em filesystem.

Sim, as listas static_*_catalog.txt sao um quebra galho para fornecer a listagem dos PDF's disponíveis. Para minimizar as inconsistencias mencionadas seria necessário que os processos de atualizaçao rodassem em horários sincronizados.

As falhas corriqueiras que eu tinha eram:

1. Por algum motivo as permissoes de execuçao dos scripts que geram os arquivos static_*_catalog.txt eram trocadas e o CRON nao conseguia atualizar as listas.
2. Falta de sincronia entre processamentos de atualizaçao do articlemeta.
2.1 Atualizar bases 
2.2 Enriquecer registros com dados de PDF's, Idiomas, etc

Esses processamentos foram configurados em stacks no Rancher.

Existia uma planilha Excel que indicava a configuraçao dos Crons nos Stacks no Rancher, com o objetivo de manter a sincronia necessária para minimizar esses problemas.

Acredito que você teria os mesmos problemas na abordagem que você mencionou, pois ainda assim teria que controlar a sincronizaçao do script que gera a lista de PDFs disponíveis com a atualizaçao do articlemeta e com a atualizaçao do SciELO SP.

Tavez, o melhor fosse garantir que os processos sao executados na hora certa, e posteriormente pensar em como indicar a existência de PDF's para o articlemeta em alguma etapa do processo de produçao dos artigos.

**Comment by anderson-attilio** [comment]
Na data de 14/08 foi relatado pelo membro da equipe de produção Odilio Junior, que um periódico não foi atualizado, texto e pdf em português.

PID S0103-73312018000200100

Prezados, bom dia,

O site scielosp.org não foi atualizado corretamente após o processamento do dia 10/08, no Periódico Physis v28n2 o texto e pdf  em português dos arquivos 0103-7331-physis-28-02-e280202 e 0103-7331-physis-28-02-e280202-pt com o título "Para defender a ciência, é necessário torná-la acessível, inteligível e significativa" e o pdf em português do arquivo 0103-7331-physis-28-02-e280204-pt com o título "A testagem do HIV entre “HSH”: tecnologias de prevenção, moralidade sexual e autovigilância sorológica" não subiram para o site final.

Att.
