### ISSUE TITLE
Nova função *get_issue_code_from_label* na interface Thrift

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/articles_meta#117]
Deve ser possível recuperar o _code_  de um _issue_ à partir do seu _label_. Exemplo: `get_issue_code_from_label(label='v25n2', journal_code='2358-2898', collection='scl') == '2358-289820130001'  # os dados não são reais`. 

O caso de uso de justifica essa mudança está no processamento do site público que é realizado com base em listas de acrônimos e rótulo de número, separados por espaço em branco.

**Comment by gustavofonseca** [comment]
@jamilatta, pode colocar exemplos de _label_ aqui?  Os casos clássicos que consigo me lembrar são: `v20n03`, `v20`. Eu sei que pode haver repetição de volumes ao longo dos anos, algo como um periódico publicar o `n20` em 2016 e também em 2018, daí o uso do ano para desambiguar.

**Comment by jamilatta** [comment]
@gustavofonseca 

Assim como conversado, devemos considerar o campo v4 da base de dados ISIS para essa atividade assumindo que o formato está correto na base e no ``scilistaxml.lst``

**Comment by gustavofonseca** [comment]
Resolvido em  6977acf
