### ISSUE TITLE
Online API unstable

### ISSUE THREAD

**Issue by joseph6x** [scieloorg/articles_meta#123]
Hi.
I am working on a project at University of Cuenca (Ecuador), which harvests publications of Ecuadorian researchers from the Scielo Article Meta API. Specifically, we are executing requests similar to this:

http://articlemeta.scielo.org/api/v1/article/?code=XX
Where XX is obtained using search.scielo.org.

It has been working well for the past months, but since a couple of weeks ago we are facing instability of the service (I am getting 'Connect to articlemeta.scielo.org:80 timed out’ errors). So, I would like to know whether the instability is caused by new quota restrictions implemented on the API or maintenance tasks on the server.

Thank you in advance for your help.

**Comment by gustavofonseca** [comment]
Hi @joseph6x. Good to know you are using our API. We are having some scalability issues that are causing timeouts and other kinds of errors. We hope to have all errors fixed very soon.

Best regards,
-Gustavo
