### ISSUE TITLE
Corrigir arquivo XML enviado para o CrossRef: Não considera suffix

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/articles_meta#166]
[1982-0216-rcefac-21-01-05-e11118.zip](https://github.com/scieloorg/articles_meta/files/3112369/1982-0216-rcefac-21-01-05-e11118.zip)
O CrossRef vem reportando erros do xml enviado.

Email:
Schematron Report for prefix(es) [10.1590]
reports@crossref.org

The results of a weekly metadata quality check are listed below. The affected DOIs were deposited successfully but the metadata attached to the DOI may need some attention.
http://data.crossref.org/reports/schematron/data/st_20190413_137505.xml
http://data.crossref.org/reports/schematron/data/st_20190413_218169.xml

Detectei que estamos desconsiderando a tag `<suffix>` para o envio de metadados para o CrossRef.

Exemplo artigo:  http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-18462019000100509&lng=en&tlng=en

No [DOI Manager](http://doi.scielo.br/deposit?code=scl_S1516-18462019000100509)

![image](https://user-images.githubusercontent.com/6084959/56660753-94322880-6676-11e9-9a7a-0d1003a0f794.png)

XML SciELO (arquivo anexo no ticket)
[1982-0216-rcefac-21-01-05-e11118.zip](https://github.com/scieloorg/articles_meta/files/3112334/1982-0216-rcefac-21-01-05-e11118.zip)

![image](https://user-images.githubusercontent.com/6084959/56660915-f723bf80-6676-11e9-940c-030e9ac344fc.png)

É necessário manter a tag de `<suffix>` para o envio ao CrossRef.

**Comment by gustavofonseca** [comment]
O XML Converter não armazena o sufixo num campo exclusivo, quando produz a base ISIS. O valor do sufixo é concatenado no sobrenome dos autores. O ArticleMeta é carregado a partir das bases ISIS, portanto não apresenta o sufixo.

Em resumo, o metadado de sufixo dos nomes dos autores é perdido ao longo do fluxo de dados, de forma que o utilitário de depósito de DOIs não pode fazer a coisa certa.

**Comment by gustavofonseca** [comment]
Este ticket poderá ser reaberto quando outro fluxo de dados estiver em operação.
