### ISSUE TITLE
Avaliar possibilidade de envio dados de <elocation-id> para o CrossRef

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/articles_meta#167]
Realizando uma pesquisa nos dados indexados no CrossRef, pude verificar que nós não enviamos dados de paginação eletrônica `<elocation-id>`, apenas paginação impressa `<fpage>` e `<lpage>`.

Exemplo arquivo com `<elocation-id>` no [DOI Manager](http://doi.scielo.br/deposit?code=scl_S2179-975X2019000100301)
![image](https://user-images.githubusercontent.com/6084959/56678568-69a59700-6699-11e9-8b86-c4b295aeb8e2.png)

Exemplo do [Como citar SciELO](http://www.scielo.br/scielo.php?script=sci_isoref&pid=S2179-975X2019000100301&lng=en&tlng=en)
![image](https://user-images.githubusercontent.com/6084959/56678486-306d2700-6699-11e9-8ccd-11154e2dc649.png)

Exemplo arquivo com `<fpage>` e `<lpage>` no [DOI Manager](http://doi.scielo.br/deposit?code=scl_S0103-21002019000100011)
![image](https://user-images.githubusercontent.com/6084959/56681135-0d457600-669f-11e9-930c-e451472f5ad6.png)

Exemplo do [Como citar](http://www.scielo.br/scielo.php?script=sci_isoref&pid=S0103-21002019000100011&lng=en&tlng=en) SciELO
![image](https://user-images.githubusercontent.com/6084959/56678911-2bf53e00-669a-11e9-984f-f64a4c568971.png)

No CrossRef, estes mesmos dois artigos aparecem:

Artigo: https://search.crossref.org/?q=10.1590%2Fs2179-975x3217

- Se elocation-id ignora a informação (em teoria porque não é enviado)

Como citar
![image](https://user-images.githubusercontent.com/6084959/56678660-9eb1e980-6699-11e9-91e4-fe1075b2b352.png)

JSON
![image](https://user-images.githubusercontent.com/6084959/56678708-bb4e2180-6699-11e9-877d-29033f59bd39.png)

Artigo: https://search.crossref.org/?q=10.1590%2F1982-0194201900003 

- Se fpage e lpage ele mostra o dado 

Como citar
![image](https://user-images.githubusercontent.com/6084959/56679196-dcfbd880-669a-11e9-86d1-bd3689daea76.png)

JSON
![image](https://user-images.githubusercontent.com/6084959/56679217-eb49f480-669a-11e9-9b27-16a6c4924992.png)

Pesquisei uma revista fora de SciELO, a Elife que usa elocation-id e notei que o CrossRef também não considera o dado.

Artigo: https://elifesciences.org/articles/36842

![image](https://user-images.githubusercontent.com/6084959/56679338-32d08080-669b-11e9-85c5-afd9c125c90b.png)

No [CrossRef,](https://search.crossref.org/?q=10.7554%2FeLife.36842) como citar:
![image](https://user-images.githubusercontent.com/6084959/56679356-411e9c80-669b-11e9-9211-6302d4685dd3.png)

JSON
![image](https://user-images.githubusercontent.com/6084959/56679492-8f33a000-669b-11e9-8b13-b2960ffd718e.png)

Solicito por favor que verifiquem se o CrossRef aceita e permite os dados de elocation-id, pois é um dado extremamente importante para citação.

Sugiro também que os metadados de paginação sendo de qualquer tipo sejam enviados para o CrossRef sempre.

**Comment by gustavofonseca** [comment]
Encontrei a seguinte implementação em um repositório do Crossref no GitHub uma xslt que transforma documentos JATS em XMLs de depósito do Crossref:

https://github.com/CrossRef/jats-crossref-xslt/blob/12eb020e4d9b0948df8938807b2132f811a3f58d/JATS2CrossRef_web.xsl#L343-L367

Ela sugere que o *elocation-id* seja representado na forma:

```xml
<publisher_item>
   <item_number item_number_type="article_number">my-elocation-id</item_number>
</publisher_item>
```

**Comment by RPostalli** [comment]
@cesarbruschetta já posso testar?

**Comment by cesarbruschetta** [comment]
> @cesarbruschetta já posso testar?

@RPostalli 
sim, isso ja se encontra no ambiente de produção do article_meta

**Comment by RPostalli** [comment]
@cesarbruschetta testei ([este artigo PC](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1806-11172019000400606&tlng=es)) e não aparece o elocation no DOI Manager
http://doi.scielo.br/deposit?code=scl_S1806-11172019000400606

E também não aparece no JSON do CrossRef
https://api.crossref.org/v1/works/10.1590/1806-9126-rbef-2018-0356

**Comment by gustavofonseca** [comment]
@RPostalli, qual é o elocation-id deste documento?

**Comment by RPostalli** [comment]
![image](https://user-images.githubusercontent.com/6084959/60345359-3af4b700-998f-11e9-8b89-7aba9ca91ed6.png)

**Comment by gustavofonseca** [comment]
O XML de depósito contém o dado na estrutura:

```xml
<publisher_item>
    <item_number item_number_type="article_number">e20180356</item_number>
    <identifier id_type="pii">S1806-11172019000400606</identifier>
</publisher_item>
```

Agora, como esse valor aparece (se aparece) no endpoint *works* do Crossref eu não sei.

**Comment by RPostalli** [comment]
Poxa verdade, ta OK no DOI Manager, não havia encontrado a tag. No CrossRef não aparece mesmo, mas me parece que eles não estão usando este dado por enquanto para nenhum provedor de dados. Obrigada.
