### ISSUE TITLE
[xmlrsps] Apresentação de aff/email

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/articles_meta#185]
### Descrição do problema
Para alguns artigos, o conteúdo apresentado em aff/email está incorreto, como por exemplo:

<img width="552" alt="Captura de Tela 2019-09-12 às 14 04 35" src="https://user-images.githubusercontent.com/505143/64804933-4acf7080-d566-11e9-92d5-a7e34163dcbc.png">

### Passos para reproduzir o problema
1. Acesse a página [http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0102-311X2007000100001&format=xmlrsps)](http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0102-311X2007000100001&format=xmlrsps)
2. Role a página até visualizar `<aff>`
4. Observe o erro apresentado dentro da tag `<email>`

### Comportamento esperado

```xml
<email>cecilia@claves.fiocruz.br</email>
```

Obs.: Isso tem impacto em document-store-migracao
https://github.com/scieloorg/document-store-migracao/issues/124

**Comment by patymori** [comment]
Apesar da exportação XMLRSPS do Article Meta não atender somente à migração, é correto alterar o retorno deste dado, visto que está assim na base?

**Comment by gustavofonseca** [comment]
Foi considerado implementar essa limpeza do dado no _document-store-migracao_? Se sim, qual o motivo de não ter seguido lá?

**Comment by robertatakenaka** [comment]
[email.txt](https://github.com/scieloorg/articles_meta/files/3950535/email.txt)

**Comment by robertatakenaka** [comment]
@patymori : Olha no xylose:
https://github.com/scieloorg/xylose/blob/cf33c5d340668c29cb6e87f1d113c7612e19256b/xylose/scielodocument.py#L2423

**Comment by patymori** [comment]
Foi decidido que, para este problema, alteraremos o Xylose para retornar emails válidos neste campo, mesmo estando dentro de tag HTML, e criaremos outro campo para retornar o dado sem tratamento.
