### ISSUE TITLE
[scieloci] Erro em data de publicação de 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/articles_meta#187]
### Descrição do problema

http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0001-37652008000100006&format=xmlwos

Gerou year com valor 0000.

```xml
<ref id="B25"><element-citation publication-type="conference"><conf-name>Seminário Internacional de Manejoem Floresta Tropical-SEMA/WWF</conf-name><conf-loc>Serra dos Carajás</conf-loc><source>Presentation</source><date><day>29</day><month>01</month><year>0000</year></date><person-group><name><surname>FEARNSIDE</surname><given-names>PM</given-names></name></person-group></element-citation></ref>
```

No entanto, no registro há a data correta, no campo v64. O correto é usar `raw.publication_date` no lugar de `raw.date` entrega a data de acordo com o tipo de referência bibliográfica, ou seja, se é tese, a data da tese, se é link, a data do acesso, e assim por diante. No entanto, a data que interessa na referência bibliográfica é a data de publicação do documento.

https://github.com/scieloorg/articles_meta/blob/05743b335f07dd97b828c375c5240e2833e58657/articlemeta/export_sci.py#L230

**Comment by joffilyfe** [comment]
@robertatakenaka eu dei uma olhada no JSON deste artigo e para a referência `25` o campo `v64` possui apenas o `ano`, sendo assim nós deveríamos remover as tags `day` e `month`?

### Screenshot
![Screen Shot 2020-03-12 at 15 57 54](https://user-images.githubusercontent.com/4604104/76557534-88ac4380-647a-11ea-9747-f3d3e5c60f93.png)

**Comment by robertatakenaka** [comment]
@joffilyfe sim, em referências o importante é o ano, raramente haverá o mês e o dia. Isso se estamos falando em publicação impressa. Já quando for publicação online, certamente haverá todos os elementos.
Use o atributo `raw.publication_date`.
