### ISSUE TITLE
Nova definição para o PID no XML retornado pela REST API de article

### ISSUE THREAD

**Issue by patymori** [scieloorg/articles_meta#190]
### Descrição da nova funcionalidade
Eu, como **desenvolvedor do SciELO Publishing Framework**, gostaria que **o XML retornado pela REST API */article/* no formato *xmlrsps* retornasse o PID do artigo na tag *article-id*, com o atributo *specific-use="scielo-v2"***, então **seria possível identificar as diferentes versões de PIDs existentes no SciELO ao longo do tempo para manter a compatibilidade entre os sistemas legados, atuais e novos**.

### Critérios de aceitação

- O valor da tag deve ser o PID atual do SciELO. Ex. de PID atual: *S0044-59671995000400161*;
- O valor da tag deve permanecer o valor do campo v880 da base ISIS de artigo
- Exemplo da tag:

```xml
<article-id pub-id-type="publisher-id" specific-use="scielo-v2">S0044-59671995000400161</article-id>
```

### Anexos
.

### Referências
Discussão sobre a definição do formato: scieloorg/PC-Programs/issues/3145

**Comment by robertatakenaka** [comment]
@gustavofonseca @patymori @jamilatta @joffilyfe 
Vocês acham que já atendemos também a versão scielo-v1? E em consequência resolve:
https://github.com/scieloorg/document-store-migracao/issues/215

**Comment by joffilyfe** [comment]
> @gustavofonseca @patymori @jamilatta @joffilyfe
> Vocês acham que já atendemos também a versão scielo-v1? E em consequência resolve:
> [scieloorg/document-store-migracao#215](https://github.com/scieloorg/document-store-migracao/issues/215)

Acho que sim @robertatakenaka, acho até que é a forma mais pragmática para resolver a issue scieloorg/document-store-migracao#215.

**Comment by gustavofonseca** [comment]
> @gustavofonseca @patymori @jamilatta @joffilyfe
> Vocês acham que já atendemos também a versão scielo-v1? E em consequência resolve:
> [scieloorg/document-store-migracao#215](https://github.com/scieloorg/document-store-migracao/issues/215)

Me parece uma boa idéia 👍
