### ISSUE TITLE
Elementos <volume>, <issue>, <fpage> e <lpage> não são inseridos no formato *xmlrsps*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/articles_meta#195]
O registro do documento `S0253-570X2018000100010`, da coleção cubana contém os metadados suficientes para que sejam representados utilizando os campos `<volume>`, `<issue>`, `<fpage>` e `<lpage>` quando no formato _xmlrsps_, entretanto os elementos não constam no XML produzido.

* Formato cru: http://articlemeta.scielo.org/api/v1/article/?collection=cub&code=S0253-570X2018000100010
* Formato xmlrsps: http://articlemeta.scielo.org/api/v1/article/?collection=cub&code=S0253-570X2018000100010&format=xmlrsps

**Comment by joffilyfe** [comment]
Em uma primeira análise consegui detectar a fonte de parte do problema. Os campos de `<issue>` e `<volume>` são inseridos no pipeline [XMLArticleMetaIssueInfoPipe](https://github.com/scieloorg/articles_meta/blob/master/articlemeta/export_rsps.py#L978), tenta-se acessar o elemento `.issue` do documento mas ele não existe e a provável causa é de que o elemento não foi carregado durante o processamento (`isis2mongo` talvez).

Acontece que não é necessário olhar para o objeto `issue` dentro do objeto `article`, as informações sobre os dados de `volume` e `número` já estão carregados no próprio `article`. É possível confirmar essa informação pelo documento [Dicionário de dados do modelo SciELO](https://docs.google.com/document/d/1SjRv_ybKB8tkDxWqz-DMWi8ENOF7kKNjDQ2fCqUd6Io/edit?usp=sharing) na página `48`.


Exemplo de verificação:

```shell
curl http://articlemeta.scielo.org/api/v1/article/\?collection\=cub\&code\=S0253-570X2018000100010 -q | jq ".article.v31"                                                                                                                                                              
[
  {
    "_": "40"
  }
]
```

```shell
curl http://articlemeta.scielo.org/api/v1/article/\?collection\=cub\&code\=S0253-570X2018000100010 | jq ".article.v32"                                                                                                                                                                 

[
  {
    "_": "1"
  }
]
```

---

Os campos `fpage` `lpages` também existe no objeto `article`.

```shell
curl http://articlemeta.scielo.org/api/v1/article/\?collection\=cub\&code\=S0253-570X2018000100010 | jq ".article.v14"

[
  {
    "f": "00",
    "l": "00",
    "_": ""
  }
]
```

Mas ao acessarmos o `raw.start_page` e `raw.end_page` o [xylose](https://github.com/scieloorg/xylose/blob/master/xylose/scielodocument.py#L2055) retorna `None` se a página for `0`, o que é o caso desse artigo.

Se esta regra for válida então não há um problema de fato no `articles_meta`. O que vocês acham @patymori @robertatakenaka @gustavofonseca @jamilatta ?

**Comment by gustavofonseca** [comment]
@joffilyfe, excelente análise. À primeira vista a implementação está equivocada ao exigir a presença do atributo `.issue`, como você bem descreveu.

> Mas ao acessarmos o raw.start_page e raw.end_page o xylose retorna None se a página for 0, o que é o caso desse artigo.
> 
> Se esta regra for válida então não há um problema de fato no articles_meta. O que vocês acham @patymori @robertatakenaka @gustavofonseca @jamilatta ?

Você se refere à regra do xylose?

**Comment by joffilyfe** [comment]
> @joffilyfe, excelente análise. À primeira vista a implementação está equivocada ao exigir a presença do atributo `.issue`, como você bem descreveu.
> 
> > Mas ao acessarmos o raw.start_page e raw.end_page o xylose retorna None se a página for 0, o que é o caso desse artigo.
> > Se esta regra for válida então não há um problema de fato no articles_meta. O que vocês acham @patymori @robertatakenaka @gustavofonseca @jamilatta ?
> 
> Você se refere à regra do xylose?

Sim, exatamente.

**Comment by joffilyfe** [comment]
> > @joffilyfe, excelente análise. À primeira vista a implementação está equivocada ao exigir a presença do atributo `.issue`, como você bem descreveu.
> > > Mas ao acessarmos o raw.start_page e raw.end_page o xylose retorna None se a página for 0, o que é o caso desse artigo.
> > > Se esta regra for válida então não há um problema de fato no articles_meta. O que vocês acham @patymori @robertatakenaka @gustavofonseca @jamilatta ?
> > 
> > 
> > Você se refere à regra do xylose?
> 
> Sim, exatamente.

Conversando com a equipe @scieloorg/scielo-brazil-developers ficou claro que a regra aplicada às propriedades `start_page` e `end_page` pelo `xylose` **está correta**. O valor `00` deve ser tratado como `None` porque **na** base `article` o preenchimento deste campo é obrigatório, sendo assim recomenda-se o seu preenchimento com `00` para **indicar a não presença de páginas**.
