### ISSUE TITLE
Erro ao atribuir os resumos traduzidos no formato xmlrsps

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/articles_meta#206]
### Descrição do problema
Durante a transformação do formato `xmlrsps` o article meta é incapaz de atribuir os resumos ao xml produzido.  O trecho de código com problema pode ser visto em:
https://github.com/scieloorg/articles_meta/blob/20713004ee3abe9f26d368a8cf6b3e0e66070c74/articlemeta/export_rsps.py#L475

### Passos para reproduzir o problema
1. Acesse o [link](http://articlemeta.scielo.org/api/v1/article/?body=true&format=xmlrsps&collection=scl&code=S0066-782X2009000900020);
2. Efetue constantes re carregamentos da página;
3. Observe o erro `Internal Server Error`;

### Comportamento esperado
A página deveria ser exibida com sucesso.

### Screenshots ou vídeos
<img width="1522" alt="Screen Shot 2020-02-04 at 11 06 46" src="https://user-images.githubusercontent.com/4604104/73751731-76820b80-473e-11ea-86fa-32261cfff4f1.png">

### Anexos
[traceback.txt](https://github.com/scieloorg/articles_meta/files/4153850/traceback.txt)

### Ambiente utilizado
N/A

**Comment by robertatakenaka** [comment]
Há erro no código e também no dado. Há dois resumos como sendo "pt".

```python
dado = "v83": [
            {
                "l": "pt",
                "_": "",
                "a": "Relatamos o caso de um paciente do sexo feminino, assintom\u00e1tica, com grande f\u00edstula bilateral da art\u00e9ria coron\u00e1ria-art\u00e9ria pulmonar. O monitoramento cl\u00ednico foi a op\u00e7\u00e3o escolhida para tratamento. Discutimos os pormenores das op\u00e7\u00f5es terap\u00eauticas, enfatizando a tend\u00eancia excessiva de utilizar a abordagem cir\u00fargica e a grande escassez de acompanhamentos cl\u00ednicos de longo prazo em pacientes assintom\u00e1ticos."
            },
            {
                "l": "pt",
                "_": "",
                "a": "We report the case of an asymptomatic female patient, with a large non-complicated bilateral coronary-pulmonary artery fistula. Clinical monitoring was the choice of treatment. We discuss the therapeutic options in depth, emphasizing the excessive tendency of the surgical approach and the great scarcity of reports on long-term clinical follow-up in asymptomatic patients."
            },
            {
                "l": "es",
                "_": "",
                "a": "Relatamos el caso de un paciente del sexo femenino, asintom\u00e1tica, con gran f\u00edstula bilateral de la arteria coronaria-arteria pulmonar. El monitoreo cl\u00ednico fue la opci\u00f3n elegida para el tratamiento. Discutimos los pormenores de las opciones terap\u00e9uticas, enfatizando la tendencia excesiva de utilizar el abordaje quir\u00fargico y la gran escasez de seguimientos cl\u00ednicos de largo plazo en pacientes asintom\u00e1ticos."
            }
        ]
```
