### ISSUE TITLE
Adicionar uma função thrift que permita retornar todos os identificadores sem a obrigatoriedade da coleção

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#61]
Adicionar uma função thrift que permita que seja retornado todos os identificadores sem a obrigatoriedade do acrônimo da coleção.

Sugiro que ``get_identifiers(from_date, until_date, limit, offset)``

**Comment by fabiobatalha** [comment]
@jamilatta 

Olhando o thrift file o metodo get_article_identifiers já permite essa ação uma vez que o atributo collection é opcional.

 list<article_identifiers> get_article_identifiers(1: optional string collection, 2: optional string from, 3: optional string until, 4: i32 limit, 5: i32 offset) throws (1:ValueError value_err, 2:ServerError server_err)

**Comment by jamilatta** [comment]
@fabiobatalha 

acredito que isso não seja verdade para a função RCP, veja só: https://github.com/scieloorg/articles_meta/blob/master/articlemeta/thrift/server.py#L94

Acredito que a alteração seja somente collection=None nos parâmetros.

**Comment by jamilatta** [comment]
@fabiobatalha 

não é verdade o que eu falei no comentário anterior o Sr. está certo, repare que o método do Databroker  aceita uma valor ``None``: https://github.com/scieloorg/articles_meta/blob/master/articlemeta/controller.py#L284 o que não está explicitado na função RPC: https://github.com/scieloorg/articles_meta/blob/master/articlemeta/thrift/server.py#L86 e tão pouco é necessário.
