### ISSUE TITLE
Adicionando algumas informações não disponíveis no formato importação do sistema de pesquisa

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#65]
Existe algumas dados que não temos no formato de exportação do article_meta para o sistema de pesquisa, ver: 
![screen shot 2015-05-05 at 11 48 29](https://cloud.githubusercontent.com/assets/373745/7475291/0b2b59ce-f31d-11e4-96ef-770c6f2e855f.png)

* Volume 
* Número
* Paginação e etc...

Considerando que temos que alterar um formato em uma outra API para obtermos esses dados, penso que devemos utilizar a capacidade do Xylose(basicamente tradução do modelo de dados do article_meta).... para termos uma maior independência para coletar esses dados, seguindo o modelo que implementamos no processamento do CitedBy.

Essa alteração visa alterar o processamento do sistema de busca de API RESTFul para Thrift.

**Comment by fabiobatalha** [comment]
Ok de acordo. Os atributos necessário devem ser implementados no Xylose.

**Comment by jamilatta** [comment]
Item realizado no PR: https://github.com/scieloorg/search-journals/pull/103
