### ISSUE TITLE
Os 437 autores de um artigo não são exibidos

### ISSUE THREAD

**Issue by ednilson** [scieloorg/articles_meta#86]
http://articlemeta.scielo.org/api/v1/article/?code=S2175-78602015000401085
chave v10 dentro de article não existe

link para o artigo:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2175-78602015000401085&lng=en&nrm=iso

**Comment by robertatakenaka** [comment]
@ednilson parece que existe sim a chave v10, mas por limitação do isis não estão todos na base ISIS. Confere?

**Comment by ednilson** [comment]
Agora está funcionando.
