### ISSUE TITLE
Periódico sem lista de fascículos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/articles_meta#90]
Ao tentarmos coletar os fascículos do periódico **Biota Neotropica** recebemos uma lista vazia, porém o periódico tem fascículos. 

Ver: http://articlemeta.scielo.org/api/v1/issue/identifiers/?issn=1676-0603

**Comment by fabiobatalha** [comment]
Corrigido, havia um problema com ISSN's do periódico.
